name: my glow
on: push

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "This is my code"
      - name: write a message
        run: echo "The code run was successfull"
      
    
